version: '3.3'

services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'user_center'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306

  app:
    build: .
    environment:
      HOST: 0.0.0.0
      PORT: 8000
      DATABASE_URL: "mysql://user:password@db/user_center"
    ports:
      - 8000
    links:
      - db
    depends_on:
      - db

  ui:
    build: ./user-ui
    volumes:
      - frontend:/data/dist

  nginx:
    image: nginx
    ports:
      - 8088:80
    volumes:
      - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend:/var/www/html
    links:
      - app
      - ui
    depends_on:
      - app
      - ui

volumes:
  frontend:
