[package]
name = "util"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "util"
path = "src/lib.rs"

[dependencies]
# passwords = { version = "^3.1.9", features = ["crypto"] }
# data-encoding = "^2.3.2"
sha_crypt = "^0.4.0"
